name: 命名規則検査

on:
  pull_request:
    types: [opened, reopened, labeled ]

jobs:
  class_diagram_scaning:
    if: ${{ github.event.label.name == 'クラス図インスペクション' }}
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
      GH_REPO: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: module installing
      run: |
        pip install pyspellchecker
        pip install nltk
        pip install spacy
        python3 -m spacy download en_core_web_sm
    - name: scaning class diagram
      run: grep -r -include='*.md' | gh pr diff ${PR_NUMBER} --name-only | xargs python3 .github/workflows/class_naming_convention_checker.py
  database_diagram_scaning:
    if: ${{ github.event.label.name == 'DB図インスペクション' }}
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: scaning db design
      run: |
        pip install pyspellchecker
        pip install nltk
        pip install spacy
        python3 -m spacy download en_core_web_sm
    - name: show diff files
      run: grep -r -include='*.md' | gh pr diff ${PR_NUMBER} --name-only | xargs python3 .github/workflows/db_naming_convention_checker.py
