name: 命名規則検査

on:
  pull_request:
    types: [opened, reopened, labeled ]

jobs:
  class_diagram_scaning:
    if: ${{ github.event.label.name == 'クラス図' }}
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
      GH_REPO: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: クラス図命名規則の検査
      run: |
        pip install pyspellchecker
        python3 .github/workflows/class_naming_convention_checker.py
    - name: show diff files
      run: gh pr diff ${number} --name-only
  database_diagram_scaning:
    if: ${{ github.event.label.name == 'DB図' }}
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: DB図命名規則の検査
      run: |
        pip install pyspellchecker
        python3 .github/workflows/database_naming_convention_checker.py
    - name: show diff files
      run: gh pr diff ${number} --name-only