name: test_label

on:
  pull_request:
    types: [opened, reopened, labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        pip install pyspellchecker
        python3 .github/workflows/naming_convention_checker.py
        ls