 name: Commit Message Linter

on:
  push:
    branches:
      - main

jobs:
  lint-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install linter tool
        run: npm install -g commitlint

      - name: Check commit messages
        run: commitlint --from=HEAD~1

      - name: Comment on pull request (if available)
        uses: actions/github-script@v4
        with:
          script: |
            const { context, github } = require('@actions/github');

            if (context.payload.pull_request) {
              const issue_number = context.payload.pull_request.number;
              const repo = context.repo.repo;
              const owner = context.repo.owner;
              const commitlintOutput = require('fs').readFileSync('./commitlint.txt', 'utf8');

              const comment = `
              **Commit Message Linting Result**

              \`\`\`
              ${commitlintOutput}
              \`\`\`
              `;

              github.issues.createComment({
                owner,
                repo,
                issue_number,
                body: comment
              });
            }

